/*
 * CALLIBRATION_Config.h
 *
 *  Created on: Aug 28, 2026
 *      Author: DELL
 */

#ifndef HAL_CALLIBRATION_CALLIBRATION_CONFIG_H_
#define HAL_CALLIBRATION_CALLIBRATION_CONFIG_H_
#define CAL_SENSOR_COUNT   5
#define CAL_SAMPLE_COUNT   20


#endif /* HAL_CALLIBRATION_CALLIBRATION_CONFIG_H_ */
